[versions]
kotlin = "1.9.23"
ktor = "2.3.9"
logback = "1.4.14"

[libraries]
# ktor
content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
core-jvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# kovibes

[bundles]
ktor = ["content-negotiation", "core-jvm", "ktor-serialization", "netty", "logback"]

[plugins]
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }